name: Code Coverage

on:
  push:
    branches: [ "test/workflow" ]
  pull_request:
    branches: [ "test/workflow" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-cov
      - name: Test with pytest and generate coverage report
        run: |
          pytest --cov=src --cov-report=xml --cov-append tests/test_api_bestbuy.py
          pytest --cov=src --cov-report=xml --cov-append tests/test_api_ebay.py
          # pytest --cov=src --cov-append tests/test_api_costco.py::test_api_costco
          # pytest --cov=src --cov-append tests/test_api_ebay.py
          # pytest --cov=src --cov-append tests/test_api_walmart.py
          # pytest --cov=src --cov-append tests/test_format*.py
          # pytest --cov=src --cov-append tests/test_url_shortener.py
          # coverage combine
          coverage xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml